# Generated by Django 3.2.5 on 2021-08-08 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('details', models.TextField()),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Food', 'Food'), ('Clothing', 'Clothing'), ('Housing', 'Housing'), ('Other', 'Other')], default='Personal', max_length=10)),
                ('date_purchased', models.DateTimeField()),
                ('expense', models.CharField(max_length=50)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
