# Generated by Django 3.2.5 on 2021-08-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_post_monthvar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='monthVar',
            field=models.DateTimeField(default='2021-08-08'),
        ),
    ]
