# Generated by Django 3.2.5 on 2021-08-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_post_monthvar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_purchased',
            field=models.DateTimeField(default='2021-08-09'),
        ),
        migrations.AlterField(
            model_name='post',
            name='monthVar',
            field=models.DateTimeField(default='2021-08-09'),
        ),
    ]
