# Generated by Django 3.2.5 on 2021-08-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20210809_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='totalExpense',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_purchased',
            field=models.DateTimeField(default='2021-08-10'),
        ),
        migrations.AlterField(
            model_name='post',
            name='expense',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='monthVar',
            field=models.DateTimeField(default='2021-08-10'),
        ),
    ]
